[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#7cb083"
backgroundColor = "#0f1412"
secondaryBackgroundColor = "#1a2721"
textColor = "#eef6ef"
font = "sans serif"

[client]
toolbarMode = "minimal"
showSidebarNavigation = false
